services:
  # Build service that creates all Docker images from Nix flake
  build-images:
    image: nixos/nix:latest
    restart: "no"
    volumes:
      - factcheck-nix_store:/nix/store
      - .:/source
      - /var/run/docker.sock:/var/run/docker.sock
      - ./compose/scripts/build-images.sh:/build-images.sh
    working_dir: /source
    command: nix-shell -p docker --run "bash /build-images.sh"

  # PostgreSQL service using the built image
  factcheck-postgres:
    image: factcheck/postgres:compose
    pull_policy: never
    depends_on:
      build-images:
        condition: service_completed_successfully
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: factcheck
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - factcheck-postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Factcheck API service using the built image
  factcheck-api:
    image: factcheck:compose
    pull_policy: never
    depends_on:
      build-images:
        condition: service_completed_successfully
      factcheck-postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: factcheck-postgres
      POSTGRES_DB: factcheck
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      FACTCHECKAPI_LISTEN_ADDRESS: ":8080"
    healthcheck:
      test: ["CMD-SHELL", "/bin/healthcheck"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - ./compose/scripts/wait-for-postgres.sh:/wait-for-postgres.sh
    command: >
      sh -c "
        chmod +x /wait-for-postgres.sh &&
        /wait-for-postgres.sh factcheck-postgres:5432 &&
        /bin/api
      "

  # Backoffice webapp service using the built image
  backoffice-webapp:
    image: factcheck/backoffice-webapp:compose
    pull_policy: never
    depends_on:
      factcheck-api:
        condition: service_healthy
    ports:
      - "3000:80"

volumes:
  factcheck-nix_store:
  factcheck-postgres_data:
