// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/kaogeek/line-fact-check/factcheck/internal/config"
	"github.com/kaogeek/line-fact-check/factcheck/internal/core"
	"github.com/kaogeek/line-fact-check/factcheck/internal/data/postgres"
	"github.com/kaogeek/line-fact-check/factcheck/internal/repo"
)

// Injectors from inject.go:

func InitializeContainerTest() (Container, func(), error) {
	configConfig, err := config.NewTest()
	if err != nil {
		return Container{}, nil, err
	}
	pool, cleanup, err := postgres.NewConn(configConfig)
	if err != nil {
		return Container{}, nil, err
	}
	queries := postgres.New(pool)
	repository := repo.New(queries, pool)
	serviceFactcheck := core.New(repository)
	container, cleanup2 := NewTest(configConfig, pool, queries, repository, serviceFactcheck)
	return container, func() {
		cleanup2()
		cleanup()
	}, nil
}
