// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/kaogeek/line-fact-check/factcheck/cmd/api/config"
	"github.com/kaogeek/line-fact-check/factcheck/cmd/api/internal/handlers"
	"github.com/kaogeek/line-fact-check/factcheck/data/postgres"
	"github.com/kaogeek/line-fact-check/factcheck/internal/repo"
)

// Injectors from inject.go:

// InitializeHandlers returns our API handler.
func InitializeHandlers() (handlers.Handler, func(), error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	conn, cleanup, err := postgres.NewConn(configConfig)
	if err != nil {
		return nil, nil, err
	}
	queries := postgres.New(conn)
	repository := repo.New(queries)
	handler := handlers.New(repository)
	return handler, func() {
		cleanup()
	}, nil
}

// InitializeContainer returns all components of interest,
// perfect for integration test or debugging
func InitializeContainer() (Container, func(), error) {
	configConfig, err := config.New()
	if err != nil {
		return Container{}, nil, err
	}
	conn, cleanup, err := postgres.NewConn(configConfig)
	if err != nil {
		return Container{}, nil, err
	}
	queries := postgres.New(conn)
	repository := repo.New(queries)
	handler := handlers.New(repository)
	container := New(conn, queries, handler)
	return container, func() {
		cleanup()
	}, nil
}
