services:
  # Build service that creates all Docker images from Nix flake
  build-images:
    image: nixos/nix:latest
    restart: "no"
    volumes:
      - ..:/source
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/build-images.sh:/build-images.sh
    working_dir: /source
    command: nix-shell -p docker --run "bash /build-images.sh"

  # PostgreSQL service using the built image
  factcheck-postgres:
    image: postgres-factcheck:16
    pull_policy: never
    depends_on:
      build-images:
        condition: service_completed_successfully
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: factcheck
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d factcheck"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Factcheck API service using the built image
  factcheck-api:
    image: factcheck
    pull_policy: never
    depends_on:
      build-images:
        condition: service_completed_successfully
      factcheck-postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: factcheck-postgres
      POSTGRES_DB: factcheck
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      FACTCHECKAPI_LISTEN_ADDRESS: :8080
    volumes:
      - ./scripts/wait-for-postgres.sh:/wait-for-postgres.sh
    command: >
      sh -c "
        chmod +x /wait-for-postgres.sh &&
        /wait-for-postgres.sh factcheck-postgres:5432 &&
        /bin/api
      "

volumes:
  postgres_data: