services:
  # Build service that creates all Docker images from Nix flake
  build-images:
    image: nixos/nix:latest
    restart: "no"
    volumes:
      - ..:/source
      - /var/run/docker.sock:/var/run/docker.sock
      - ./scripts/build-images.sh:/build-images.sh
    working_dir: /source
    command: nix-shell -p docker --run "bash /build-images.sh"
