name: Deploy backoffice-webapp to Cloudflare Pages

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy webapp
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Build webapp with Nix
        run: |
          echo 'Building webapp with Nix...'
          nix build .#backoffice-webapp
          echo 'Build completed successfully'

      - name: Deploy to Cloudflare Pages (Production)
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy result --project-name=${{ secrets.CLOUDFLARE_PROJECT_NAME }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
