name: build go
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    name: Build go binaries with Nix
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      ARTIFACT_FACTCHECK: "factcheck-bin-nix_${{ matrix.os }}"
      ARTIFACT_FOO: "foo-bin-nix_${{ matrix.os }}"

    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: "0"

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build factcheck with Nix
        run: |
          nix build .#factcheck
          mkdir -p $ARTIFACT_FACTCHECK
          cp result/bin/* $ARTIFACT_FACTCHECK/ || true

      - name: Build foo with Nix
        run: |
          nix build .#foo
          mkdir -p $ARTIFACT_FOO
          cp result/bin/* $ARTIFACT_FOO/ || true

      - name: Build version with Nix
        run: |
          nix build .#version
          cp result/bin/version.txt $ARTIFACT_FACTCHECK/ $ARTIFACT_FOO/

      - name: Upload Go binaries
        uses: actions/upload-artifact@v4
        with:
          name: build_result-nix_${{ matrix.os }}
          path: |
            ${{ env.ARTIFACT_FACTCHECK }}
            ${{ env.ARTIFACT_FOO }}

