name: lint go
on:
  push:
    branches:
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull requests. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  golangci:
    name: lint with Nix
    runs-on: ubuntu-latest
    strategy:
      matrix:
            gomod:
              - factcheck
              - pillars
              - foo
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: golangci-lint with Nix
        run: |
          cd ${{ matrix.gomod }}
          nix run nixpkgs#golangci-lint -- run --timeout=5m