name: test go
on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  test:
    name: Test code
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

        go-version:
          - stable
          - "" # empty string = read version from go.mod

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    env:
      ARTIFACT_FOO: "foo-test_result-go${{ matrix.go-version }}_${{ matrix.os }}.json"
      ARTIFACT_BAR: "bar-test_result-go${{ matrix.go-version }}_${{ matrix.os }}.json"
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          fetch-depth: "0"

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          go-version-file: "./foo/go.mod"
          cache: false
          check-latest: true

      - name: Test foo
        run: |
          cd foo;
          echo "PWD: $pwd"
          echo "Testing foo and writing JSON report to $ARTIFACT_FOO"
          go test -race -count=1 -json ./... > $ARTIFACT_FOO

      - name: Test bar
        run: |
          cd bar;
          echo "PWD: $pwd"
          echo Testing bar and writing JSON report to $ARTIFACT_BAR
          go test -race -count=1 -json ./... > $ARTIFACT_BAR

      - name: Upload Go test results
        uses: actions/upload-artifact@v4
        with:
          name: test_result-go${{ matrix.go-version }}_${{ matrix.os }}
          path: |
            foo/${{ env.ARTIFACT_FOO }}
            bar/${{ env.ARTIFACT_BAR }}

