name: lint webapp
on:
  push:
    branches:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      WEBAPP_DIR: backoffice-webapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ env.WEBAPP_DIR }}

      - name: Run format check
        run: npm run format:check
        working-directory: ${{ env.WEBAPP_DIR }}

      - name: Run lint
        run: npm run lint
        working-directory: ${{ env.WEBAPP_DIR }}

      # Ensure commit can build?
      - name: Run build
        run: npm run build
        working-directory: ${{ env.WEBAPP_DIR }}
