name: lint webapp
on:
  push:
    branches:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      WEBAPP_DIR: backoffice-webapp

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Install dependencies and run checks
        run: |
          nix develop --command bash -c "
            cd $WEBAPP_DIR
            echo 'Installing dependencies...'
            npm ci
            
            echo 'Running format check...'
            npm run format:check
            
            echo 'Running lint...'
            npm run lint
            
            echo 'Running build...'
            npm run build
            
            echo 'All checks completed successfully!'
          "
